<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CSharpAPI">
      <HintPath>..\..\..\..\Program Files (x86)\TWS_API\samples\CSharp\IBSampleApp\bin\Release\CSharpAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
